### ISSUE TITLE
Reproducible crash with Save As Default Smart Raster Palette

### ISSUE THREAD

**Issue by WolfInABowl** [turtletooth/tahoma#106]
Video:
https://streamable.com/k2lg7b#

Repro steps (upon starting Tahoma):
1. Create a Smart Raster Level and use the `Save As Default Smart Raster Palette` command.
2. Create a new Scene via `File -> New Scene`
3. Select a cell in Col1 / Select the camera column's header then Col1's header

Notes:
I was only able to get the crash with Smart Raster, following the same steps with the other 2 level types didn't trigger it.
Although a Smart Raster level does not need to exist to call the `Save As Default Smart Raster Palette` command, the creation of a Smart Raster level in step 1 is necessary for the crash to occur.
Overwriting an already present default palette does not seem to be a factor, the crash still occurs from a fresh installation.
This crash was initially discovered by Rodney, also on a Windows machine.

Tahoma version: 1.0 Beta 4 (Jul 27)
OS: Win 10

**Comment by manongjohn** [comment]
Thanks for testing.  I can reproduce the steps. Will look into it.
