### ISSUE TITLE
Feature request: Support RAW format for Stop Motion

### ISSUE THREAD

**Issue by turtletooth** [turtletooth/tahoma#11]
Add raw support.

**Comment by hansjacobwagner** [comment]
the camera can save the raw on a flash drive so you don't have to wait for the transfer of the large images. So after the shooting and the scene is in place - the raw could be colorgraded and outputted as 24bit .tiff placed in Tahoma and brought in for final rendering. I think the work flow must be like that.

**Comment by turtletooth** [comment]
#120
