### ISSUE TITLE
Some default window sizes are too small

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma#112]
**Describe the bug**
When opening Tahoma for the first time, the Timeline, Style Editor, and Stop Motion Controls windows are too small. Expanding the program window/going fullscreen does expand the Timeline. However the width of the Style Editor & Stop Motion Controls remain too narrow without manual adjustment. The Stop Motion Controls window is the worst - it's barely visible at all.

**To Reproduce**
List steps to reproduce the behavior.
1. Open Tahoma for the first time using a computer without adjusting the program window size
2. Go fullscreen

**Expected behavior**
The Timeline should show at least 1 row by default. The Stop Motion Controls should be visible. Ideally, all the tabs in the Style Editor should be visible. Personally, I'd also like the program window to fill the whole screen on open.

**Screenshots**
<img width="960" alt="Screen Shot 2020-08-04 at 11 12 57 AM" src="https://user-images.githubusercontent.com/21159116/89311347-dc931100-d643-11ea-8516-b462548d501b.png">
<img width="961" alt="Screen Shot 2020-08-04 at 11 13 15 AM" src="https://user-images.githubusercontent.com/21159116/89311350-ddc43e00-d643-11ea-9e15-d3f39971024c.png">

**Device Information:**
 - OS: macOS 10.14.6 & 10.15.4
 - Tahoma Version: Beta (8/4/20)

**Comment by turtletooth** [comment]
Thanks for the info.  What is the resolution of those screens?  I built the rooms to default to a good size at 1920 x 1080 but we can tweak them.

**Comment by artisteacher** [comment]
1680 x 1050 & 1440 x 900. Thanks!
