### ISSUE TITLE
New guides and grids

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma#122]
@DarrenTAnims requested that new guides and grids be added to the field guide options.

@DarrenTAnims - do you have the file that you were requesting be added?

**Comment by turtletooth** [comment]
Thanks for clarifying.  I hadn't played with it yet and thought it was a revision to field guides.  I agree that revising field guides makes the most sense.

**Comment by DarrenTAnims** [comment]
I agree MJ. It's very much a workaround. I would much prefer if the field guide button (to the right of the safe areas) had the same right click option, to select the guide. But it doesn't.

**Comment by melieconiek** [comment]
I use the safe area dropdown to draw camera relative guides like this. The guides scale properly with different camera sizes. It would nice have this in it's own menu--and have it be possible to draw lines and circles for these. I prefer to have small crosses at the intersections on a third's guide for example.

Grids that don't change scale with the camera should be separate from this.

![image](https://user-images.githubusercontent.com/42298081/90561209-59f37100-e16e-11ea-8c85-bf1f76a16760.png)
![image](https://user-images.githubusercontent.com/42298081/90561243-68da2380-e16e-11ea-8ac8-11a3596703df.png)
![image](https://user-images.githubusercontent.com/42298081/90561266-7394b880-e16e-11ea-9158-eb42aa468bba.png)

**Comment by DoctorRyan** [comment]
Perspective grids are super useful and it would be nice if we can add them
to OT in some form or another.  With the Assistant Tool not looking to well
right now, we should start exploring other alternatives.

**Comment by turtletooth** [comment]
At the risk of being shunned. . . do we need field guides?  Could we repurpose that section?

**Comment by melieconiek** [comment]
I use the field guides--I could do with just a plain grid, though. I'd wonder if anyone uses the safe area tool these days.

To simplify what I was saying: It would be nice if we had an option to define camera relative guides like the safe area feature _and_ could define stationary guides/grids like the field guide.

**Comment by manongjohn** [comment]
I was thinking of how to expand the current Field Guide feature to keep what is there but also allow for customizable guides similar to assistant tool.

At the very minimum could make it similar to how the Safe Area currently works in terms of customizing your own list and grids.

**Comment by melieconiek** [comment]
I wouldn't be against re-purposing both. You could keep a standard field guide in your new stationary guide menu.

**Comment by melieconiek** [comment]
On the subject of customizable guides, one thing I have to do a lot is draw floor/ceiling perspective guides. It would be great if this was built into Tahoma.

Something tweakable like Lazy Nezumi's perspective guide would be great. Doesn't need to snap either, just needs the grid. It would need a tweakable horizon, rotation, and FoV. Have it draw a nice floor and optional ceiling grid and save this info in the current scene.

![_demo](https://user-images.githubusercontent.com/42298081/90564491-75ad4600-e173-11ea-99f6-dc636ed8d207.gif)
