### ISSUE TITLE
The hand tool - toggle?!

### ISSUE THREAD

**Issue by hansjacobwagner** [turtletooth/tahoma#125]
**Question**
Ask a question related to Tahoma.

**Comment by artisteacher** [comment]
I'm not seeing that in macOS. If I am using the brush and then press space to trigger panning, pan as needed, then release the space key, it returns to the brush tool.

**Comment by melieconiek** [comment]
You might have `Hand Tool` mapped to spacebar in the Configure Shortcuts window. I had a similar issue when I imported my keybindings from OpenToonz.
