### ISSUE TITLE
Increase (Scene Cast) Icon Preview Images Size

### ISSUE THREAD

**Issue by Mainman002** [turtletooth/tahoma#128]
I have been Dragging / Dropping a lot of character images from the (Scene Cast) window, but the Icon preview is almost unusable due to the image size (I know this request might add extra performance cost, but it would be nice to at least scale the icon preview images for use on larger monitors)

* Scale slider to increase icon preview zoom (doesn't change image resolution, just preview scale)
* Import option to increase preview image resolution (will increase cache size and maybe performance drain)
* Options in settings to increase the default preview resolution / zoom when opening project scenes

This is how it looks currently
![image](https://user-images.githubusercontent.com/11281480/91660127-f0dafa00-ea99-11ea-9d97-9c7cbf2990fe.png)

Concept image of what I think would look good when working with cast images
![Icon Zoom Propsal](https://user-images.githubusercontent.com/11281480/91661161-d7d54780-ea9f-11ea-90a2-c1678fb082f7.png)

Hopefully this request isn't too much of a fight to achieve, but I think it would really help improve workflows that involve manually placing images

**Comment by DarrenTAnims** [comment]
Instead of using the scene cast window, you could (should) use the Level Strip. Just choose the level from the drop down then you'll be shown the preview thumbnails. And you can change the thumbnail size in the preferences (restart OT after changing the size)

**Comment by turtletooth** [comment]
@DarrenTAnims is correct.  The level strip is the way to go here.

**Comment by Mainman002** [comment]
Sorry for keeping this open but how does the (Level Strip) menu help / work? it only shows a single image, then I select that 1 image from my list, and it takes over the whole preview window just to drag my image to the timeline. In my case it's almost worse working with the (Level Strip) menu
![image](https://user-images.githubusercontent.com/11281480/91742166-6ec30200-eb7b-11ea-9a0a-76d034a4cd29.png)

**Comment by Mainman002** [comment]
But it does have the zoom feature I was needing, so how do I show the other images in my separate portrait folders?
![image](https://user-images.githubusercontent.com/11281480/91742417-dda05b00-eb7b-11ea-887f-0dbc49a5293e.png)

**Comment by turtletooth** [comment]
If all of your images were named as an image sequence (bob.0001.png), the level strip would see them all.

**Comment by Mainman002** [comment]
ahh I understand. . . so doing this I can't name them differently? like "David_QU_Eyes_Closed.01.png" it actually becomes "David.01.png" . . . hmm sounds like I have some renaming to do :) thank you for your help sorry I'm just a strugglin new user to apps like this. It's very easy to learn though compared to other apps. (Love the performance)

**Comment by turtletooth** [comment]
Glad it's making sense.  No worries about the questions.  We've all been there.
