### ISSUE TITLE
Lip Sync Thumbnail Display

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma#131]
**Describe the bug**
In the apply lip sync data window, the thumbnail display has several issues. Smart raster lines are a little more pixelated than the normal display. Raster lines are broken/non-contiguous. Vector levels are the worst. The thumbnails might have a strip of noise across the top. They are cropped to display only part of the image but the image is duplicated. 

**To Reproduce**
List steps to reproduce the behavior.
1. Right-click on a raster, smart raster, or vector cell in the Xsheet/Timeline
2. Select "Apply Lip-Sync Data to Column"

**Screenshots**
Vector:
<img width="351" alt="Screen Shot 2020-08-29 at 1 37 54 AM" src="https://user-images.githubusercontent.com/21159116/91780905-e79b7b80-ebc6-11ea-8062-13aa38eded5e.png">
Raster:
<img width="176" alt="Screen Shot 2020-08-29 at 1 48 55 AM" src="https://user-images.githubusercontent.com/21159116/91780914-ebc79900-ebc6-11ea-9c8b-82f0074240bf.png">
Smart Raster:
<img width="174" alt="Screen Shot 2020-08-31 at 8 35 08 PM" src="https://user-images.githubusercontent.com/21159116/91782582-84f8ae80-ebcb-11ea-97a6-61065393b907.png">

**Device Information:**
 - OS: macOS 10.14.6 & 10.15.4
 - Tahoma Version: Beta
 - GPU: 
 - GPU Driver Version:

**Comment by turtletooth** [comment]
Does it do this in OpenToonz too?

**Comment by artisteacher** [comment]
It does. It looks like it started with [https://github.com/opentoonz/opentoonz/pull/3288](https://github.com/opentoonz/opentoonz/pull/3288)

**Comment by turtletooth** [comment]
Fixed.

**Comment by turtletooth** [comment]
I'm going to close this since raster is no worse than raster in the level strip.

**Comment by artisteacher** [comment]
The vector thumbnail is perfect! Thanks!
