### ISSUE TITLE
Timeline clipped when starting Tahoma maximized

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma#134]
**Describe the bug**
The top of the timeline appears to be clipped by the panes above it when I have my room arranged a certain way and Tahoma starts up maximized.

![image](https://user-images.githubusercontent.com/19245851/92196470-5a159100-ee3d-11ea-8953-d80ff9b4f00e.png)

I recall another user on Discord also encountered a similar issue, though I don't know what their room layout looked like.

**To Reproduce**
1. Add a Command Bar and rearrange the 2D room to look like this
![image](https://user-images.githubusercontent.com/19245851/92196567-8d582000-ee3d-11ea-86a5-cc0a13005704.png)
2. Maximize Tahoma
3. Restart Tahoma -> timeline becomes clipped

It only appears to happen when starting maximized in the 2D room with this configuration.

It corrects itself when you unmaximize.  When you restart Tahoma unmaximized, it's also ok.  If you start Tahoma maximized but in another room, then switch to this one, it's also ok. 

**Device Information:**
 - OS: Windows 10
 - Tahoma Version: 1.0

**Comment by turtletooth** [comment]
I can confirm this, but I can't figure out why it's happening.

**Comment by turtletooth** [comment]
Scratch that.  I found it.
