### ISSUE TITLE
Tahoma window expands right unexpectedly

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma#139]
**Describe the bug**
For some reason, the Tohama window will unexpectedly expand to the right.  Not sure what causes it.  When it does that, I can't easily shrink it back, as if it now has a minimum width.  

This is a problem when the window isn't maximized but covers most of the screen it expands right off screen,

NOTE: I use a virtual macOS for testing purposes so not sure if it's related to my environment, but OTX does not do this. Reporting it in case others see the same thing.

**Screenshots**
![auto-expands](https://user-images.githubusercontent.com/19245851/92290381-e7aabc80-eee1-11ea-963e-3ffd41eafc49.gif)

**Device Information:**
 - OS: virtual macOS 10.15
 - Tahoma Version: 1.0
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by turtletooth** [comment]
That's the status bar expanding to show all the tool tips for the brush tool.  Any ideas on how to balance window size and communicate messages?

**Comment by manongjohn** [comment]
Ah. I see. I notice it does it in Windows, if the window is small enough.

Need clip the text.  Need to factor in font width and size of box.  I think I do that with NoteText cells.

**Comment by artisteacher** [comment]
On my 15in macBook Pro, the window gets expanded beyond the screen size when the brush is active on a raster level.
<img width="1680" alt="Screen Shot 2020-09-04 at 8 29 09 PM" src="https://user-images.githubusercontent.com/21159116/92292843-5b9e9200-eeed-11ea-85dc-3b9442872898.png">
In this case there's definitely room for less margin between tips.

**Comment by turtletooth** [comment]
I think I found a 1 line fix.  Yay!

**Comment by turtletooth** [comment]
Fixed and pushed to master.
