### ISSUE TITLE
Crash on close in macOS

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma#141]
**Describe the bug**
Sometimes closing Tahoma from the 2D room causes a crash. When this happens, it resets any size adjustments to the windows in the 2D room back to the default. A crash notification doesn't come up, but there's a crash report visible in Console. If this happens once, it happens every time closing from the 2D room.

**To Reproduce**
List steps to reproduce the behavior.
1. Close Tahoma with the 2D room open (closing method makes no difference)

**Screenshots**
<img width="628" alt="Screen Shot 2020-09-05 at 12 04 49 PM" src="https://user-images.githubusercontent.com/21159116/92309050-08b9ee80-ef70-11ea-9dbb-258bad66a6b8.png">

It looks like this might be the problem:
<img width="715" alt="Screen Shot 2020-09-05 at 12 09 09 PM" src="https://user-images.githubusercontent.com/21159116/92309113-a44b5f00-ef70-11ea-95e3-ce4d2b4af46f.png">

**Device Information:**
 - OS: [macOS 10.14.6 & 10.15.6]
 - Tahoma Version: [1.0.1]

**Comment by turtletooth** [comment]
I haven't experienced that, but I'll take a look.

**Comment by manongjohn** [comment]
I see that with the macOS OTX builds also. Only see that on macOS. I started looking into that but didnt get very far with it.

**Comment by artisteacher** [comment]
Thanks for looking into it. It's annoying having to adjust the windows every time on open.

There are 2 other files with the same warning. I wonder if they cause some of the random crashes on OT.
<img width="265" alt="Screen Shot 2020-09-05 at 1 46 54 PM" src="https://user-images.githubusercontent.com/21159116/92310659-7d942500-ef7e-11ea-8701-aedef9a6ff3d.png">

**Comment by artisteacher** [comment]
It looks like several developers on github fixed similar issues in their header files. So it might be a matter of adjusting orientation.h.  I have no clue how to make a virtual destructor though. 

On the student computers the crash report pops up on every close. It doesn't make for a great first impression.
