### ISSUE TITLE
Palette problem

### ISSUE THREAD

**Issue by ilbarbudo** [turtletooth/tahoma#143]
**Describe the bug**
Changin the palette color doesn't change the draw color

**To Reproduce**
List steps to reproduce the behavior.
1.Start drawing
2.Change the color in the palette
3.The palette change but the drawing no

**Expected behavior**
Drawing and filling in different colors.

**Screenshots**
![TahomaColorProblem](https://user-images.githubusercontent.com/70839456/92322525-12a42600-f032-11ea-9b1a-4df3d3213cd1.png)

**Device Information:**
 - OS: Windows 10 Pro
 - Tahoma Version: 1.0.1
 - GPU: Intel UHD 630
 - GPU Driver Version: 27.20.100.8587

**Comment by jeremybullock** [comment]
I've never seen that.  Do you get that still after closing and reopening Tahoma?

**Comment by artisteacher** [comment]
What does your Timeline look like? Is there any chance you’re on a different level than the squiggle?

**Comment by ilbarbudo** [comment]
Thanks for the reply.

It appear every time and I have only 1 level.
![AnotherShotTahoma](https://user-images.githubusercontent.com/70839456/92449036-ba982b80-f1b9-11ea-87ce-6a040b24b6e4.png)

**Comment by ilbarbudo** [comment]
Update:
I've used 3 different colors and every times the "Brush Tool" and the "Geometry Tool" draw black.
The "Style picker tool" doesn't recognize the "Brush tool" and the "Geometry Tool" drawings but perceives them as transparent colors; it identify the "Smart Raster Paint Tool" colors right.
The  "Smart Raster Paint Tool" draw always grey.
The  "RGB Picker Tool" work fine and "see" the right color

By the way, the "Geometry Tool" in rectangle mode round 3 edges.

![TahomaBehavior](https://user-images.githubusercontent.com/70839456/92454537-e5d24900-f1c0-11ea-9c81-897fc3218d56.png)

In my experience with Blender, the origin of the graphic problems is, many times, the Intel UHD Graphics.

Best Regards!

**Comment by manongjohn** [comment]
Check the options under the View menu. Did you enable something by accident?

**Comment by ilbarbudo** [comment]
YES!!! 

It was the "Transparency check" active.
Deactivated it al the colors seem to work fine.

Thanks to all and sorry of wasting your time!

Best Regards!

**Comment by manongjohn** [comment]
No problem. Glad it was resolved.

Development Side note: Might be good to add some sort of indicator somewhere (status or title bar?), when you have certain View modes activated so you know.

**Comment by jeremybullock** [comment]
Good sleuthing skills @manongjohn 

I agree on an indicator.
