### ISSUE TITLE
Xsheet

### ISSUE THREAD

**Issue by YankaWarm** [turtletooth/tahoma#144]
Hi
How i can get a Xsheet window like opentoonz ?
When i choose menu: Window -> Xsheet i get "Timeline" window every time (
**Question**
Ask a question related to Tahoma.

**Comment by manongjohn** [comment]
Strange.  When I use Window ->Xsheet,  I get an Xsheet.

If you right-click any column header in the timeline, choose `Toggle Orientation` to switch it to Xsheet mode.

**Comment by YankaWarm** [comment]
Yeah! 
Its work for me, thank you!
