### ISSUE TITLE
A feature which I would love you to add to Tahoma

### ISSUE THREAD

**Issue by TerryficANIM8S** [turtletooth/tahoma#146]
Please add a cutter tool like the one in toonboom . That would be really helpful and save time making lineart.Thank you

**Comment by manongjohn** [comment]
Can you explain or provide a video of what feature of Toonboom's cutter tool you are looking to see?

**Comment by TerryficANIM8S** [comment]
https://youtu.be/j3E5ozgNggo
Look at 8:48min of this video to see what Im talking about,Iam starting a big project and wanted to use Tahoma as my animation software ,and if there is one tool I would love to see in Tahoma ,its this one. Thanks

**Comment by manongjohn** [comment]
That feature you are asking for already exists.  It's available for Vector levels under the Eraser tool.  Switch the mode to `Segment` and swipe away.

**Comment by TerryficANIM8S** [comment]
Thank you so much
