### ISSUE TITLE
Does Tahoma have custom brushes,and is it possible for me to make my own

### ISSUE THREAD

**Issue by TerryficANIM8S** [turtletooth/tahoma#152]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Comment by manongjohn** [comment]
Similar to regular OT, you can create your own custom styles.  They just need to be saved in specific tahomastuff folders using certain formats.

...\Tahoma\tahomastuff\library\custom styles
...\Tahoma\tahomastuff\library\textures
...\Tahoma\tahomastuff\library\vector brushes

If you look in those folders, you can see the formats that are likely supported.

For any Vector styles, you should create it within Tahoma and save the .PLI file under vector brushes or custom styles.  I would recommend copying 1 that is already there and use that as a template. 

You can also load in MyPaint brush sets if you find some you like. You can even create your own MyPaint brushes if you know how and use those as well, either by placing it in the tahomastuff\library\mypaint brushes folder or if you have MyPaint already installed, it will automatically read in those brushes as well.
