### ISSUE TITLE
Bug- Interface goes outside of screen

### ISSUE THREAD

**Issue by msMJ263** [turtletooth/tahoma#159]
**Describe the bug**
When in full-screen mode, Tahoma's interface expands past the limits of my screen. (Resolution is 1366 x 768)
Going to windowed mode seems to "reset" the interface's placement, but the issues repeat all over again, causing minor to major inconvenience.

**To Reproduce**
List steps to reproduce the behavior.

1. draw on the canvas (which makes a new frame on the timeline)
--
1. make a new frame on the timeline
2. draw on the canvas
--
1. have a new scene, empty
2. briefly hover cursor towards the toolbar

--
1. click an empty frame next to a frame already drawn on

**Expected behavior**

I simply expected the program to consistently fit the screen at all times.

**Screenshots**
![image](https://user-images.githubusercontent.com/71145196/92954245-bcb3f180-f428-11ea-9015-72e2466b847a.png)
![image](https://user-images.githubusercontent.com/71145196/92954265-c89fb380-f428-11ea-9f85-2fe55cf460bf.png)
![image](https://user-images.githubusercontent.com/71145196/92954284-ce959480-f428-11ea-8821-c3f83e104615.png)
![image](https://user-images.githubusercontent.com/71145196/92954301-d35a4880-f428-11ea-97e5-6a5ba2064181.png)
![image](https://user-images.githubusercontent.com/71145196/92954325-d9e8c000-f428-11ea-88ae-6aa15fa28071.png)

**Device Information:**
 - OS: Windows 10 Home
 - Tahoma Version: Tahoma v1.0.1
 - GPU: Intel (R) HD Graphics 520
 - GPU Driver Version: 27.20.100.8476

**Comment by artisteacher** [comment]
Is this the same as #139? As a workaround, turning off the status bar (under the view menu) should help.

**Comment by jeremybullock** [comment]
If this is the same as #139 the download release for 1.0.1 was swapped out after #139 was fixed.  Can you try downloading the most recent version again?

**Comment by msMJ263** [comment]
> Is this the same as #139? As a workaround, turning off the status bar (under the view menu) should help.


> If this is the same as #139 the download release for 1.0.1 was swapped out after #139 was fixed. Can you try downloading the most recent version again?

I don't know how I didn't see that. Sorry it's my first time reporting a bug. haha Thank you both for the quick response! I'll try downloading it again now!
