### ISSUE TITLE
CONCRT140.dll not found

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma#167]
A few Windows users are reporting they are getting CONCRT140.dll not found when trying to start Tahoma.

It's possible some Windows systems don't have this installed, so it might be good to include it with the Windows releases as other MSVS *140.dlls are included.

**Comment by jeremybullock** [comment]
I added the file to the release.

**Comment by jeremybullock** [comment]
Thanks for helping out as usual @manongjohn
