### ISSUE TITLE
Switching projects

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma#183]
I started a new scene and realized I was in the wrong Project and wanted to switch to an existing one I already have but I don't see how you can switch Projects on a current scene.

There is no `File -> Change Project` option and in OT, at least, when you switched Projects in the Startup dialog box, it automatically switched projects for you, but that no longer works because it's not a dropdown.

Am I missing something?  If so please let me know.

Otherwise, I would suggest that the `File -> New Project` be changed to `Change Project` and  the popup dialog allow you to enter a path to an existing one or create a new.

**Comment by RattusaurusRex** [comment]
File -> Project Management -> Switch Project

**Comment by artisteacher** [comment]
You can change the project from the startup window too. Click on ... next to the project location to choose a different project. Also opening a scene from a different project changes to that project. 

In the browser, you can also change projects by clicking on the empty circle next to a project name to turn it red.

**Comment by manongjohn** [comment]
Sorry, my bad.  I had built the latest master and was running in RelWithDebug mode through VS and didnt have the File -> Project Management option, just New Project.  Apparently I forgot to update my tahomastuff folder with the latest and was still seeing the original menu options.
