### ISSUE TITLE
hex code?

### ISSUE THREAD

**Issue by Holly1001** [turtletooth/tahoma#190]
**Is your feature request related to a problem? Please describe**
I am always frustrated when I want to animate a character with specific colors and I can't get the exact colors I need.

**Describe the solution you'd like**
however, if you give the option to input hex codes, then this issue would be solved.

**Comment by artisteacher** [comment]
Click on the hamburger menu icon at the bottom right of the style editor:
<img width="175" alt="Screen Shot 2020-09-20 at 8 10 52 PM" src="https://user-images.githubusercontent.com/21159116/93725468-7a538880-fb7d-11ea-8e49-f84e4e0dea0c.png">
