### ISSUE TITLE
Crash when creating New Scene

### ISSUE THREAD

**Issue by mjcairns** [turtletooth/tahoma#198]
**Describe the bug**
If I have a scene open and create a new scene without saving, the program quits unexpectedly.

**To Reproduce**
1. Create or open a scene. Draw a few strokes.
2. Click "File>New Scene". When prompted, click "Discard Changes" and "New Scene Anyway".
3. Select the brush tool and try to draw.

**Expected behavior**
To be able to start a new scene without any problem.

**Screenshots**

**Device Information:**
 - OS: Windows 10
 - Tahoma Version: [e.g. Nightly (2020-01-10)]
 - GPU: NVIDIA GTX 980
 - GPU Driver Version: 456.38

**Comment by artisteacher** [comment]
I'm not seeing this on macOS.

**Comment by manongjohn** [comment]
I am also not able to replicate on Win10

**Comment by mjcairns** [comment]
It seems to be working now. I think my computer was taking stupid pills after a recent update, but now it's fine.
