### ISSUE TITLE
Frame range didn't work on vector level when I had auto fill selected

### ISSUE THREAD

**Issue by DarrenTAnims** [turtletooth/tahoma#204]
In the latest build (24th Sept), I used the auto fill option, which worked well, but if I set the frame range to anything but No, it didn't work.

Steps
- Added a vector level
- Ticked auto close & auto fill
- Changed range to Linear
- On frame 1, drew a shape, it didn't show the auto closing yet. That's fine.
- Moved to frame 8. Drew a shape.

Outcome
It just extended the first drawing up to frame 7, then the 2nd drawing was on frame 8.

**Comment by jeremybullock** [comment]
Did you create blank drawings in the region first?

**Comment by DarrenTAnims** [comment]
No I didn't. I'd left blank frames, a gap between them. I assumed (always bad) that it would create them for me.

**Comment by jeremybullock** [comment]
It needs the frames to exist.  I think even normal frame range doesn't create the frames.

**Comment by DarrenTAnims** [comment]
Thank you. I've tested this and if I create blank frames first, the fill range works. Amazing..
