### ISSUE TITLE
Pasting an image into an empty frame (from the clipboard) asked about creating a level, but didn't (and didn't need to)

### ISSUE THREAD

**Issue by DarrenTAnims** [turtletooth/tahoma#205]
While in a column with a level in it, with some drawings in it. If I move to the next empty frame (no drawings there), then pasted an image from my clipboard. Tahoma thought was larger, it offered the create new level question popup, but when I selected to create a new level, it pasted into a new drawing in the current level. AND it fits in the new level. It's almost like it didn't think it could fit, but when I said create a new level, it had another think and decided that it could.
Here's a  recording:

![ScreenCapture](https://user-images.githubusercontent.com/28575907/94163946-5bf0d400-fe80-11ea-8633-8cd661707836.gif)

**Comment by jeremybullock** [comment]
Feature?

**Comment by jeremybullock** [comment]
Any chance you could share that exact image?

**Comment by DarrenTAnims** [comment]
I can't, because I just used the windows snipping tool (Windows key+Shift+S) to get it. But I've just tried it by clicking my PrtScn button and get the same result.

**Comment by jeremybullock** [comment]
This should now work.
