### ISSUE TITLE
Shortcut editing really dodgy?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#210]
I have the feeling this can't be right, and I'm missing something here, but when I try and change a keyboard shortcut, it doesn't seem to do anything 90% of the time.

A specific example: I wanted to change the view zoom (+/-) to CTRL+ and CTRL- (...just because my other programs have that, and I want to keep things similar for 'muscle memory' reasons).

But, when I attempt to change it, visually nothing happens.  The indicated keyboard shortcut in the list/display doesn't change.  I even tried clearing the shortcut (which works), but again, nothing visually happens (nor does it appear to have worked, when I try the shortcut after exiting the editor).

I managed to change ONE of the two shortcuts once or twice.... (Always the same one, the zoom out).  I do literally the same thing to change both zoom in and out, yet only the zoom out works... when it does.  Almost feels like a broken keyboard thing, but it isn't.

I guess I have to see if it's specific to the zoom shortcuts, by trying to edit any of the others.  At first, I thought that maybe modifiers weren't supported, but the CTRL- shortcut DID actually work... when I did manage to actually change it.

I'll look into it further, but I just wanted to bring that up, and see if maybe this is a known thing, or there's some know factor that can cause this.

Oh, I should also point out, sometimes, even though there visually was no change in the shortcut in the list (still appeared to be set to the default Tahoma shortcut), attempting to use the same shortcut in the other shortcut (ex. use CTRL+ in the zoom OUT shortcut field) would trigger a 'This shortcut is used for Zoom In'... implying that the change (for Zoom In) DID actually work, even though it is not visually indicated (list shows old/original shortcut).  So, maybe an screen/text updating issue in the shortcut list?

Win7Pro, 32gigs RAM, Tahoma1.0

**Comment by artisteacher** [comment]
On macOS the shortcut list immediately updates if I change a shortcut - and the new shortcut works. 

As a workaround for now, you could try editing one of the shortcut .ini files (stuff folder -> profiles -> layouts -> shortcuts). They'll open in any basic text editor. After making changes, restart Tahoma. Actually, if you haven't restarted your computer lately, you might want to try that too.

**Comment by ladlon** [comment]
Great idea.  I may do that.

I'm getting the feeling that my work machine, overall, seems to have some kind of graphical update issue.  I've noticed some programs don't seem to be redrawing certain things properly... for example, Affinity having some small sections of an image not properly scaling up when you zoom the screen in/out.  No idea what that could be caused by.

If you can move the shortcut window while it's open, I should try moving it after changing an item, and see if that forces a screen update.

Wacky....

**Comment by artisteacher** [comment]
In that case, if you can, you should check & see if there's an update for the graphics driver. Windows doesn't always notify about the most recent driver. It's more reliable checking the websites from Intel or etc.

**Comment by ladlon** [comment]
UPDATE: Today, the keyboard shortcut edit screen seems to be working fine.  I'll have to keep an eye on this, and see if the issue creeps in, perhaps triggered by some other action/factor.
