### ISSUE TITLE
Small changes to the paste image popup dialog

### ISSUE THREAD

**Issue by DarrenTAnims** [turtletooth/tahoma#213]
Not really a bug, but just to finish the chat in the Discord today, with suggestions (happy to be ignored if they don't make sense, as always).

Pasting a larger image into the frame directly after a level with a smaller size, will show a popup:

![image](https://user-images.githubusercontent.com/28575907/94274003-0e866c80-ff3d-11ea-81c0-e9d7a068844a.png)

This brings up 3 suggested changes:
1. Change the dialog text to mention resize instead of crop: The pasted image is larger than the current level. Pasting in this level will resize the image. What do you want to do?
2. Change the text on Paste in place to: Paste resized image or Paste in current level
3. Change the text on Create a new level to: Paste into new level

Demo:
![ScreenCapture](https://user-images.githubusercontent.com/28575907/94273929-f7e01580-ff3c-11ea-8cf3-4ef61adb5eff.gif)

**Comment by jeremybullock** [comment]
Once the new appveyor builds, could you try that please?
