### ISSUE TITLE
Merging outputs and creating node instances? [SOLVED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#215]
Hello.  Two questions...

Is there a node/means to merge multiple outputs from upstream nodes in the schematic view into a single output?  I know I can apply a global effect by putting FX nodes between the XSheet and Output nodes, but sometimes you don't want to apply it to ALL level nodes, but still have quite a number that you do (...so, essentially, you want to apply a global FX to a group of items, but not all of the ones in the scene).  Any way to address that?

Second question... Is there a means to create instances of an FX node?  By that, I mean copies of them, but ones whose settings that are automatically updated when the master node's settings are adjusted (...so you can have a 'global' effect applied to multiple items, yet not have manually adjust every node when changes are required.

UPDATE: Is the OverFX node what I would use to merge multiple node outputs? Seems to work.

**Comment by WolfInABowl** [comment]
For the first question, as you said, the `Over` node is currently the best solution. However, you must specify the stacking order manually, meaning that you lose the automatic link to the XSheet that the `XSheet` node provides.

For the second question, you can right-click on a node a select `Create Linked FX`.
Any changes to any one of the linked nodes will be propagated to the rest.
Linked nodes will have a green wire connecting them together e.g.
![image](https://user-images.githubusercontent.com/42905003/94298643-62ee1400-ff5e-11ea-9610-cdc54805098f.png)
You can unlink any linked nodes to make their settings unique, but I haven't found a way to link existing nodes together.

**Comment by ladlon** [comment]
Awesome.  Thanks, WolfInABowl.
