### ISSUE TITLE
RGB colour picker seems to create chaos

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#219]
Sorry, this one is very odd, and I can't supply too much helpful info on it currently.

All I can say, is that I have a scene with a character (multi-level, parented), and a photo background.  All is good, until I selected the character's eyebrow, selected the RGB colour picker, and then clicked on the character's hair (different level than the eyebrow).

The colour seemed to get transferred fine, but suddenly the view shifts (moves in closer), and from that point on, scrolling the view/scene results in the character (all of him) panning fine, but the background moves slower, as if it is far into the Z plane (parallax effect).  In fact, the background IS actually significantly smaller than it should be, further leaning towards the theory that it has been pushed far back down the Z axis.  Nothing seems to return the scene to normal (where the background moves the same amount as the character during a view pan).

I'm very new to Tahoma, so there's a lot I have to get used to and learn.  However, from what I can see (assuming I'm understanding the display and values properly), the background image is still on the same Z plane/depth as the character (both appear to be in the same depth in the 3D view, and both have the same Z value displayed in the upper context bar).

Saving the file and reloading it doesn't fix it, either.

On top of that, there is an additional 'casualty' of the eyedropper use, in that when you do something like drag select with the mouse, the resulting selection box is FAR offset from the mouse pointer position (and perhaps the resulting scaling of the selection frame is not equal to the amount of movement of the mouse)... almost like IT is on a different Z plane, too.

Sorry I can't really provide more.  Whatever it is, it is definitely triggered by the RGB eyedropper, and (I'd assume) affects the bottommost level (in my case, the photographic background image).

If there's anything you guys want me to try, please let me know.

Win7Pro, 32gigs RAM, Tahoma1.0

UPDATE: Using the Rectangle mode of the RGB colour picker seems to work fine (no view shift).  So, it seems it might be exclusive to the Normal mode of the RGB colour picker.

UPDATE2: As artisteacher rightfully points out, this appears to be the same issue reported in OpenToonz (since 2018, it seems).

**Comment by artisteacher** [comment]
This sounds like a reported bug on OT - [https://github.com/opentoonz/opentoonz/issues/1717](https://github.com/opentoonz/opentoonz/issues/1717)

**Comment by ladlon** [comment]
Yep, you are totaly right, artisteacher.  Thanks for pointing that thread out to me.  The screen captures are showing the same kind of parallax thing I was experiencing.

Well, good to see that it's 'a real thing', and that support knows about it already.
