### ISSUE TITLE
Maximized version not fullscreen

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#229]
For some reason, Tahoma is no longer scaling itself out to full screen when maximized.  Any idea what might be causing that, or how I can fix that?  Right now, I can only put it in windowed mode (or whatever you'd call the 'double window' icon at the top right of the window) and manually pull all the edges to fit the screen.  But, clicking on the Maximized icon (single window icon) puts it into a sort of windowed mode, where it's only about 50-75% of the screen size.

Win7Pro

**Comment by artisteacher** [comment]
Can you share some screenshots that show the problem?

**Comment by ladlon** [comment]
Nothing much to show... just the Tahoma app window not maximizing.  Can't seem to get it to go back to expanding to the full monitor size.  Can't find anything in the settings, and you can't adjust the window size when it's in Maximize mode (only in Restore Down mode).


![TahomaNotMaximized](https://user-images.githubusercontent.com/71803483/94347956-94bab580-0006-11eb-933e-5d5b2460fef2.JPG)

**Comment by ladlon** [comment]
I did some research, and found a tip that ended up fixing it.  Set the Run value in the shortcut's properties to Maximize.

Shouldn't have worked, since it should just end up the same (broken) maximized size as before (as clicking on the Maximize icon at the top corner does... but, it must have reset something, because (so far) it seems that fixed it.

**Comment by ladlon** [comment]
Is there some config that stores the size of the main window?  It seems to open with the same window size (in Maximized mode), regardless of what size/aspect I scale the main window to in Restore Down mode, so it's not related to that (I'd assume).

Something is telling it to make the window that size, even if I have the shortcut start it in Maximized mode.  It's as if it thinks the screen resolution is smaller than it really is.

**Comment by jeremybullock** [comment]
I know what’s going on. I’ll fix it.

**Comment by jeremybullock** [comment]
Fixed in #236
