### ISSUE TITLE
Empty level allow "Delete Unused Styles" to delete color 0

### ISSUE THREAD

**Issue by justburner** [turtletooth/tahoma#231]
**Describe the bug**
Empty column allow "Palette > Delete Unused Styles" to delete color 0 (Transparency).

**To Reproduce**
1. Select an empty column
2. On the Palette window, right click "colors" tab and select "Delete Unused Styles"
3. Tahoma ask if you want to delete indices 0, 1

**Expected behavior**
Tahoma shouldn't allow to delete color 0

**Screenshots**
![GIF Video](https://cdn.discordapp.com/attachments/453998574427176962/759559444459159622/ezgif-7-0d890a070b0b.gif)
![MP4 Video](https://cdn.discordapp.com/attachments/713452707742220298/759557092033560636/2020-09-27_00-21-47.mp4)

**Further testing**
This issue doesn't occur on OT since it doesn't allow default palette to show without a level being created.

**Comment by jeremybullock** [comment]
@manongjohn Do you want to take this one, or should I?

**Comment by manongjohn** [comment]
I can take a look at it.

**Comment by jeremybullock** [comment]
Thanks!
