### ISSUE TITLE
Ability to rename Macro effects [SOLVED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#238]
Hello again...  I was surprised to see that you can't seem to give MacroFX (group of nodes packaged into a single node) a custom name.  Would be particularly useful, seeing as it could describe the content and/or funtion of the MacroFX node (without having to open it to remind yourself).  I couldn't find any way to name it, so I'm assuming you can't currently?

Maybe even have it do a popup 'inside view' window when you hover the mouse over it... or at least a text-based node list?

**Comment by artisteacher** [comment]
I think it's ctrl-click on the name?

**Comment by ladlon** [comment]
Ha!  It took a few tries, but a double CTRL-click does it!  Thanks for pointing that out.

Ugh, it's 1am... Time to call it a night.

Cheers!
