### ISSUE TITLE
Error launching Tahoma from scene file [SOLVED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#243]
Hi.  So, I've never been able to launch Tahoma by double-clicking a Tahoma scene file (from my project folder's Scenes folder).

The Tahoma splash screen comes up, but then an error window comes up saying:

Unidentified or empty: Software\Tahoma\Tahoma\ToonzRoot 

I'm assuming this is a registry thing.  In the registry, there is only one item, and indeed regedit claims the value is blank.

I tried reinstalling Tahoma (as the error message suggests), but it didn't fix it.  I'm suprised there's a registry item with a portable program (...although I won't pretend to understand much of the registries in general).

Up to now, I've simply launched Tahoma itself, and then clicked on a scene in the Recent Projects window... which works, but I would still like to be able to launch by clicking the scene files themselves (in my project directory).

Is this a known issue, or is there some factor on my side I should look into?

**Comment by artisteacher** [comment]
It works fine on macOS, once I set the computer to have Tahoma open the scene files. That's actually disabled by default.

**Comment by ladlon** [comment]
Ya, I made sure to use 'Open With...' on the scene file ensure that Tahoma was the program associated with it.  It does launch Tahoma, but hits the error message just after the splash screen appears.

The issue obviously seems to be that registry item being black... whatever that is.  It's obviously finding the Tahoma exe fine, since the splash screen is launching, but it seems some initialization is getting tripped up... and only if you launched via the scene file (as opposed to launching an 'empty' Tahoma and loading the scene from within).

**Comment by manongjohn** [comment]
I believe, when using the exe or a shortcut, it usually looks in the working directory which is either where the .exe is started or defined in the shortcut itself. Lauching by file association apparently launches it in the current directory so when it can't find the stuff folder there, it looks at Windows registry. Tahoma is a portable and purposely does not use Windows registry so it can run from anywhere.

If works for macOS probably because the tahomastuff is inside the .app.

**Comment by ladlon** [comment]
Yup, that makes sense as a technical explanation, for sure...

Still, I wonder if you couldn't have a fallback in Tahoma, where if it can't find whatever it's looking for, it looks in a user-defined location... just for such a situation.

I totally get and appreciate the portable concept.  I like portable software, as it's less registry mess, and uninstalls cleanly.  I'm all in on that.

It's just a muscle-memory / workflow thing of mine that's clashing with that now... At the start of any work session (whether in Tahoma or any other program), I tend to open up the project directory (as I know I'll probably be accessing notes and graphics from within that throughout the session anyway), and instinctively click on the project file to launch it.  Just kind of does two tasks with one action.

At least the Recent Projects feature kind of addresses that.  I just want to avoid having to drill through directories in the file browser (in Tahoma) every time.  I suppose some shortcuts at the root might address that.

No biggie... just a 'preference' on my part.

**Comment by manongjohn** [comment]
If you used the method outlined in #207 to make it a fixed application, then it should allow you to launch by file association.

**Comment by ladlon** [comment]
Ya, I may end up doing that.  Again, not a big deal, so I'm not stressing about it (and why I didn't put it as a Bug or Feature Request).

Just kind of wanted to see if that's normal, or if there was something glitching on me.  I seem to be a magnet for software glitches!

**Comment by manongjohn** [comment]
No prob. It's all good to get Tahoma as stable as possible. I know another OT user who has a knack for finding obscure bugs. Keeps me busy finding and fixing the cause. 😁

Btw, you can just close your tickets if you are satisfied (i know...rather subjective) with the answer.

**Comment by ladlon** [comment]
Ah!  Thanks for pointing out the self-closing feature.  Didn't see that!

Alright, I'll be using that from now on.

'Learning all the time....'
