### ISSUE TITLE
Improper matting with PaletteFilter node [SOLVED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma#245]
I'm hoping someone can give me some theories as to why this is happening.  I'm seemingly following the instructions (from a video tutorial) exactly, yet getting different results (...actually it 'works', but has a flaw).

I'm doing the usual 'putting an iris into an eyeball shape' thing, using the MatteIn and PaletteFilter (To bring back the outlines) nodes.  It's all working, except the matte is not matching the width of the outline, so there's partial overlap happening.

Originally, I was using a custom Vector stroke, and figured it was because of that (...and thinking maybe Tahoma only works with the standard stroke).  So I tried regular strokes, but the same issue happened...  So, I thought maybe it had issues with multi-thickness strokes, so I made it all even... Still had the issue.

I tried various combos of settings for the PaletteFilter, but, still no go.

I've attached a picture, showing the tree, the PaletteFilter settings, and the resulting matting (and checked several times that it matched that shown in the video, in which it worked fine).

Any theories/suggestions?

![PaletteFilterIssue](https://user-images.githubusercontent.com/71803483/94375916-f5202480-00e4-11eb-9e2e-8dd86b3e9084.JPG)

Win7Pro

**Comment by WolfInABowl** [comment]
For vector levels, the fill extends up to the center line.
This means that as you are using the white fill as the matte, the pupils' visibility extends up to the center line, covering part of the outline.

My preferred way of matting one vector shape into another would be by using the `Texture` node.
The `Texture` node replaces all of the pixels belonging to the `Source` input with the provided `Texture` input.

Here's a graph, with the `Texture` node set to the style index of the sclera:
![image](https://user-images.githubusercontent.com/42905003/94377811-32ec6f80-011c-11eb-9dee-0e0786dd3f1b.png)
And the result:
![image](https://user-images.githubusercontent.com/42905003/94377828-51526b00-011c-11eb-970c-08d38d1947f2.png)

You can see that the pupil is correctly matted but the rest of the sclera is removed.
To fix this, we can use an `Over`/`OverIno` node like this:
![image](https://user-images.githubusercontent.com/42905003/94377849-7a72fb80-011c-11eb-8c16-7505160fb312.png)
Which gives this correct result:
![image](https://user-images.githubusercontent.com/42905003/94377861-88288100-011c-11eb-9d7b-522c2df66ac1.png)

**Comment by ladlon** [comment]
Ya, I figured it was a centerline thing....

That's an interesting alternative method you have there.  I can't say I've seen that anywhere else.

I'll try that out.  Thanks!

**Comment by ladlon** [comment]
Ya!  That seems to work.  I have the Texture node set to Keep colour index 1.

Nice!  Okay, that's another issue off the list.

It was a brutal day today, but ended with my two main issues finally being sorted out.

Cheers!
