### ISSUE TITLE
Crash when starting in a maximized state

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma#80]
**Describe the bug**
When I open Tahoma, maximize it and then close it.  The next time I open Tahoma, it crashes when it tries display the windows.

**To Reproduce**
List steps to reproduce the behavior.
1. Open Tahoma
2. Maximize the window
3. Close Tahoma
4. Open Tahoma again

The splash screen displays, but crashes when the windows finally tries to display.

NOTE: To reset the windows, delete tahomastuff\profiles\layouts\settings.xxx\mainwindow.ini

**Device Information:**
 - OS: Windows 10
 - Tahoma Version: Beta 1

**Comment by turtletooth** [comment]
Thanks for the issue.

That's a first I've heard of it.  Did you build this version, or is the is the off the shelf beta?

If you built it, what version of Qt are you using?

Again, if you built it, can you comment out mainwindow.cpp lines 1303-1321 and see if that works.

**Comment by turtletooth** [comment]
I just tried with a fresh download of the beta and couldn't reproduce.

**Comment by manongjohn** [comment]
I found it first in my local build and then confirmed it was happening also in the downloaded beta version.

It's crashing on line 348 in docklayout.cpp. I'll see if commenting out the lines you mentioned somehow fixes it.

**Comment by manongjohn** [comment]
Commenting out the piece of code you suggested fixed the problem.

If I leave the code as is but change the `nt->setInterval(10); ` to 50, a number I chose randomly, it doesn't crash.  Perhaps my system is slower than yours is so it needs a little more time?  Older or less powerful systems may have problems even with 50 so I'm not sure if that is the best way to fix this.

Can you explain what that piece of code is supposed to help with? Since it is a problem on my system, I may be able to find an alternate way to fix it so others don't run into this issue.

**Comment by turtletooth** [comment]
This change was to make all panels REALLY go back to their original positions on restarting Tahoma.  For example, in Stop Motion, I don't need many layers, so I can use a really small timeline.  But it would go back to a bigger size upon reopening.  This was an attempt to fix that.  It works, when it doesn't crash systems. . .

I'm going to change the timer to 100 and see if that works.

**Comment by manongjohn** [comment]
I was playing around with a different fix but finally realized why you put that logic in.  I ran with 50 and 60 ok, so 100 should be fine.

**Comment by turtletooth** [comment]
If you have a better option, I'd love to know.  This is a hack.

**Comment by turtletooth** [comment]
Changed it in #83 
We can reopen if needed.
